services:
  - type: web
    name: chatrix-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_ENDPOINT
        value: https://your-backend-url.onrender.com

  - type: web
    name: chatrix-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3005
